import { SpecimenRecord } from "./types";

export const sampleData: SpecimenRecord[] = [
  {
    gbifID: "912048762",
    scientificName: "Dimorphandra gardneriana Tul.",
    eventDate: "1985-01-09",
    recordNumber: "1349",
    recordedBy: "Lewis, G.P.",
    cluster_num_id: "7896",
    decimalLongitude: null,
    decimalLatitude: null,
    locality: "Piaui",
    verbatimElevation: null,
  },
  {
    gbifID: "912091237",
    scientificName: "Phoradendron Nutt.",
    eventDate: "1985-01-13",
    recordNumber: "1356",
    recordedBy: "Lewis, G.P.",
    cluster_num_id: "7896",
    decimalLongitude: -42.7,
    decimalLatitude: -5.333333,
    locality: "Rod. Br 316, 1 Km from Dermeval Lobao in direction of Teresina.",
  },
  {
    gbifID: "912112914",
    scientificName: "Poeppigia procera (Poepp. ex Spreng.) C.Presl",
    eventDate: "1985-01-08",
    recordNumber: "1338",
    recordedBy: "Lewis, G.P.; Freire, F.M.T.; Lopes, A.S.; Teixeira, G.A.; Alcoforado, F.G.",
    cluster_num_id: "7896",
    decimalLongitude: -41.33333,
    decimalLatitude: -7.416667,
    locality: "7km along trackway to Lagoa Achada, start of trackway is 9km south of Jaicós along the BR 407 to Petrolina.",
  },
  {
    gbifID: "912114216",
    scientificName: "Chamaecrista eitenorum (H.S.Irwin & Barneby) H.S.Irwin & Barneby",
    eventDate: "1985-01-09",
    recordNumber: "1347",
    recordedBy: "Lewis, G.P.; Freire, F.M.T.; Lopes, A.S.; Teixeira, G.A.; Alcoforado, F.G.",
    cluster_num_id: "7896",
    decimalLongitude: -41.66667,
    decimalLatitude: -6.5,
    locality: "24km from Valença to Lagão do Sítio. By farmstead.",
  },
  {
    gbifID: "1051235998",
    scientificName: "Rhynchanthera brachyrhyncha Cham.",
    eventDate: "1985-01-28",
    recordNumber: "1375",
    recordedBy: "Lewis, G.P.; Hatschbach, G.G.; Cervi, A.C.; Dombrowski, L.",
    cluster_num_id: "7896",
    decimalLongitude: -49.75,
    decimalLatitude: -25.5,
    locality: "Rod. BR 376 Curitiba to Ponta Grossa. Serra São Luiz.",
  },
  {
    gbifID: "5103935637",
    scientificName: "Philodendron appendiculatum Nadruz & Mayo",
    eventDate: "1985-01-29",
    recordNumber: "1403",
    recordedBy: "Lewis, G.P.; Hatschbach, G.; Cervi, A.C.; Dombrowski, L.",
    cluster_num_id: "7896",
    decimalLongitude: -48.66667,
    decimalLatitude: -25.5,
    locality: "Reserva Biológica Sapitanduva, near Morretes; Mata",
  },
];
